apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-monitor
  namespace: messaging
  labels:
    release: kube-prometheus
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  namespaceSelector:
    matchNames:
      - messaging
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics